In [78]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # data visualization
import seaborn as sns # statistical data visualization
%matplotlib inline

In [79]:

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
train.dropna()
test.dropna()

Unnamed: 0      id  Gender      Customer Type  Age   Type of Travel  \
0                0   70172    Male     Loyal Customer   13  Personal Travel   
1                1    5047    Male  disloyal Customer   25  Business travel   
2                2  110028  Female     Loyal Customer   26  Business travel   
3                3   24026  Female     Loyal Customer   25  Business travel   
4                4  119299    Male     Loyal Customer   61  Business travel   
...            ...     ...     ...                ...  ...              ...   
103899      103899   94171  Female  disloyal Customer   23  Business travel   
103900      103900   73097    Male     Loyal Customer   49  Business travel   
103901      103901   68825    Male  disloyal Customer   30  Business travel   
103902      103902   54173  Female  disloyal Customer   22  Business travel   
103903      103903   62567    Male     Loyal Customer   27  Business travel   

           Class  Flight Distance  Inflight wifi service  \
0       Eco Plus              460                      3   
1       Business              235                      3   
2       Business             1142                      2   
3       Business              562                      2   
4       Business              214                      3   
...          ...              ...                    ...   
103899       Eco              192                      2   
103900  Business             2347                      4   
103901  Business             1995                      1   
103902       Eco             1000                      1   
103903  Business             1723                      1   

        Departure/Arrival time convenient  ...  Inflight entertainment  \
0                                       4  ...                       5   
1                                       2  ...                       1   
2                                       2  ...                       5   
3                                       5  ...                       2   
4                                       3  ...                       3   
...                                   ...  ...                     ...   
103899                                  1  ...                       2   
103900                                  4  ...                       5   
103901                                  1  ...                       4   
103902                                  1  ...                       1   
103903                                  3  ...                       1   

        On-board service  Leg room service  Baggage handling  Checkin service  \
0                      4                 3                 4                4   
1                      1                 5                 3                1   
2                      4                 3                 4                4   
3                      2                 5                 3                1   
4                      3                 4                 4                3   
...                  ...               ...               ...              ...   
103899                 3                 1                 4                2   
103900                 5                 5                 5                5   
103901                 3                 2                 4                5   
103902                 4                 5                 1                5   
103903                 1                 1                 4                4   

        Inflight service  Cleanliness  Departure Delay in Minutes  \
0                      5            5                          25   
1                      4            1                           1   
2                      4            5                           0   
3                      4            2                          11   
4                      3            3                           0   
...                  ...          ...                         

In [80]:
train.shape

(103904, 25)

In [81]:
train.describe()

Unnamed: 0             id            Age  Flight Distance  \
count  103904.000000  103904.000000  103904.000000    103904.000000   
mean    51951.500000   64924.210502      39.379706      1189.448375   
std     29994.645522   37463.812252      15.114964       997.147281   
min         0.000000       1.000000       7.000000        31.000000   
25%     25975.750000   32533.750000      27.000000       414.000000   
50%     51951.500000   64856.500000      40.000000       843.000000   
75%     77927.250000   97368.250000      51.000000      1743.000000   
max    103903.000000  129880.000000      85.000000      4983.000000   

       Inflight wifi service  Departure/Arrival time convenient  \
count          103904.000000                      103904.000000   
mean                2.729683                           3.060296   
std                 1.327829                           1.525075   
min                 0.000000                           0.000000   
25%                 2.000000                           2.000000   
50%                 3.000000                           3.000000   
75%                 4.000000                           4.000000   
max                 5.000000                           5.000000   

       Ease of Online booking  Gate location  Food and drink  Online boarding  \
count           103904.000000  103904.000000   103904.000000    103904.000000   
mean                 2.756901       2.976883        3.202129         3.250375   
std                  1.398929       1.277621        1.329533         1.349509   
min                  0.000000       0.000000        0.000000         0.000000   
25%                  2.000000       2.000000        2.000000         2.000000   
50%                  3.000000       3.000000        3.000000         3.000000   
75%                  4.000000       4.000000        4.000000         4.000000   
max                  5.000000       5.000000        5.000000         5.000000   

        Seat comfort  Inflight entertainment  On-board service  \
count  103904.000000           103904.000000     103904.000000   
mean        3.439396                3.358158          3.382363   
std         1.319088                1.332991          1.288354   
min         0.000000                0.000000          0.000000   
25%         2.000000                2.000000          2.000000   
50%         4.000000                4.000000          4.000000   
75%         5.000000                4.000000          4.000000   
max         5.000000                5.000000          5.000000   

       Leg room service  Baggage handling  Checkin service  Inflight service  \
count     103904.000000     103904.000000    103904.000000     103904.000000   
mean           3.351055          3.631833         3.304290          3.640428   
std            1.315605          1.180903         1.265396          1.175663   
min            0.000000          1.000000         0.000000          0.000000   
25%            2.000000          3.000000         3.000000          3.000000   
50%            4.000000          4.000000         3.000000          4.000000   
75%            4.000000          5.000000         4.000000          5.000000   
max            5.000000          5.000000         5.000000          5.000000   

         Cleanliness  Departure Delay in Minutes  Arrival Delay in Minutes  
count  103904.000000               103904.000000             103594.000000  
mean        3.286351                   14.815618                 15.178678  
std         1.312273                   38.230901                 38.698682  
min         0.000000                    0.000000                  0.000000  
25%         2.000000                    0.000000                  0.000000  
50%         3.000000                    0.000000                  0.000000  
75%         4.000000                   12.000000                 13.000000  
max         5.000000                 1592.000000               1584.000000

In [82]:
train['satisfaction'] = train['satisfaction'].replace(to_replace='neutral or dissatisfied', value=0)
train['satisfaction'] = train['satisfaction'].replace(to_replace='satisfied', value=1)
train = pd.get_dummies(train)
train.iloc[:,5:].head(5)

Departure/Arrival time convenient  Ease of Online booking  Gate location  \
0                                  4                       3              1   
1                                  2                       3              3   
2                                  2                       2              2   
3                                  5                       5              5   
4                                  3                       3              3   

   Food and drink  Online boarding  Seat comfort  Inflight entertainment  \
0               5                3             5                       5   
1               1                3             1                       1   
2               5                5             5                       5   
3               2                2             2                       2   
4               4                5             5                       3   

   On-board service  Leg room service  Baggage handling  ...  satisfaction  \
0                 4                 3                 4  ...             0   
1                 1                 5                 3  ...             0   
2                 4                 3                 4  ...             1   
3                 2                 5                 3  ...             0   
4                 3                 4                 4  ...             1   

   Gender_Female  Gender_Male  Customer Type_Loyal Customer  \
0              0            1                             1   
1              0            1                             0   
2              1            0                             1   
3              1            0                             1   
4              0            1                             1   

   Customer Type_disloyal Customer  Type of Travel_Business travel  \
0                                0                               0   
1                                1                               1   
2                                0                               1   
3                                0                               1   
4                                0                               1   

   Type of Travel_Personal Travel  Class_Business  Class_Eco  Class_Eco Plus  
0                               1               0          0               1  
1                               0               1          0               0  
2                               0               1          0               0  
3                               0               1          0               0  
4                               0               1          0               0  

[5 rows x 25 columns]

In [83]:
train.shape
train

Unnamed: 0      id  Age  Flight Distance  Inflight wifi service  \
0                0   70172   13              460                      3   
1                1    5047   25              235                      3   
2                2  110028   26             1142                      2   
3                3   24026   25              562                      2   
4                4  119299   61              214                      3   
...            ...     ...  ...              ...                    ...   
103899      103899   94171   23              192                      2   
103900      103900   73097   49             2347                      4   
103901      103901   68825   30             1995                      1   
103902      103902   54173   22             1000                      1   
103903      103903   62567   27             1723                      1   

        Departure/Arrival time convenient  Ease of Online booking  \
0                                       4                       3   
1                                       2                       3   
2                                       2                       2   
3                                       5                       5   
4                                       3                       3   
...                                   ...                     ...   
103899                                  1                       2   
103900                                  4                       4   
103901                                  1                       1   
103902                                  1                       1   
103903                                  3                       3   

        Gate location  Food and drink  Online boarding  ...  satisfaction  \
0                   1               5                3  ...             0   
1                   3               1                3  ...             0   
2                   2               5                5  ...             1   
3                   5               2                2  ...             0   
4                   3               4                5  ...             1   
...               ...             ...              ...  ...           ...   
103899              3               2                2  ...             0   
103900              4               2                4  ...             1   
103901              3               4                1  ...             0   
103902              5               1                1  ...             0   
103903              3               1                1  ...             0   

        Gender_Female  Gender_Male  Customer Type_Loyal Customer  \
0                   0            1                             1   
1                   0            1                             0   
2                   1            0                             1   
3                   1            0                             1   
4                   0            1                             1   
...               ...          ...                           ...   
103899              1            0                             0   
103900              0            1                             1   
103901              0            1                             0   
103902              1            0                             0   
103903              0            1                             1   

        Customer Type_disloyal Customer  Type of Travel_Business travel  \
0                                     0                               0   
1                                     1                               1   
2                                     0                               1   
3                                     0                               1   
4                                     0                               1   
...                                 ...                             ...   
103899     

In [86]:
train_labels = np.array(train['satisfaction'])
train_features = train.drop(labels=['satisfaction'], axis=1)
train_feature_list = list(train.columns)

In [87]:
train = np.array(train)

In [60]:
test['satisfaction'] = test['satisfaction'].replace(to_replace='neutral or dissatisfied', value=0)
test['satisfaction'] = test['satisfaction'].replace(to_replace='satisfied', value=1)
test = pd.get_dummies(test)
test.iloc[:,5:].head(5)
test_labels = np.array(test['satisfaction'])
test_features = test.drop(labels=['satisfaction'], axis=1)
test_feature_list = list(test.columns)

In [88]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)

Training Features Shape: (103904, 29)
Training Labels Shape: (103904,)
Testing Features Shape: (25976, 29)
Testing Labels Shape: (2, 25976)


In [94]:
train_features = train_features.fillna(0)
test_features = test_features.fillna(0)

In [90]:
from sklearn.ensemble import RandomForestRegressor
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# Train the model on training data
rf.fit(train_features, train_labels);

In [108]:
predictions = rf.predict(test_features)
predictions = np.round(predictions)
# Calculate the absolute errors
errors = abs(predictions - test_labels)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2))

Mean Absolute Error: 0.04


In [109]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print("Confusion Matrix:")
print(confusion_matrix(test_labels,predictions))
print("Classification Report:")
print(classification_report(test_labels,predictions))

Confusion Matrix:
[[14248   325]
 [  624 10779]]
Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.98      0.97     14573
           1       0.97      0.95      0.96     11403

    accuracy                           0.96     25976
   macro avg       0.96      0.96      0.96     25976
weighted avg       0.96      0.96      0.96     25976



[0.984 1.    0.    ... 0.    1.    0.   ]
[1 1 0 ... 0 1 0]


(array([], dtype=int64), array([], dtype=int64))

(array([], dtype=int64), array([], dtype=int64))

array([[0.00000e+00, 7.01720e+04, 1.30000e+01, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       [1.00000e+00, 5.04700e+03, 2.50000e+01, ..., 1.00000e+00,
        0.00000e+00, 0.00000e+00],
       [2.00000e+00, 1.10028e+05, 2.60000e+01, ..., 1.00000e+00,
        0.00000e+00, 0.00000e+00],
       ...,
       [1.03901e+05, 6.88250e+04, 3.00000e+01, ..., 1.00000e+00,
        0.00000e+00, 0.00000e+00],
       [1.03902e+05, 5.41730e+04, 2.20000e+01, ..., 0.00000e+00,
        1.00000e+00, 0.00000e+00],
       [1.03903e+05, 6.25670e+04, 2.70000e+01, ..., 1.00000e+00,
        0.00000e+00, 0.00000e+00]])

array([1., 0., 1.])

1.0