In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # data visualization
import seaborn as sns # statistical data visualization
%matplotlib inline

In [2]:
data = 'breast-cancer-wisconsin.csv'
df = pd.read_csv(data, header=None)
names = ['code', 'clump-thickness', 'cell-size', 'cell-shape', 'marginal-adhesion',
'single-epithelial', 'bare-nuclei', 'bland-chromatin', 'normal-nucleoli', 'mitosis', 'Class']
df.columns = names

In [3]:
df = df.replace(to_replace='?', value=0)

In [4]:
X = df.iloc[:,1:10]

In [5]:
y = df.iloc[:,10]
df.head()

code  clump-thickness  cell-size  cell-shape  marginal-adhesion  \
0  1000025                5          1           1                  1   
1  1002945                5          4           4                  5   
2  1015425                3          1           1                  1   
3  1016277                6          8           8                  1   
4  1017023                4          1           1                  3   

   single-epithelial bare-nuclei  bland-chromatin  normal-nucleoli  mitosis  \
0                  2           1                3                1        1   
1                  7          10                3                2        1   
2                  2           2                3                1        1   
3                  3           4                3                7        1   
4                  2           1                3                1        1   

   Class  
0      2  
1      2  
2      2  
3      2  
4      2

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 9)

In [7]:
from sklearn.neural_network import  MLPClassifier
clf = MLPClassifier(hidden_layer_sizes = (10,10,10), max_iter=500).fit(X_train, y_train)

C:\Users\Logan\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [8]:
from sklearn.model_selection import cross_val_score
print("cross Validation scores") 
cross_val_score(clf,X_train,y_train,cv=5)

cross Validation scores


C:\Users\Logan\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\Logan\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\Logan\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


array([0.95535714, 0.97321429, 0.97321429, 0.96428571, 0.94594595])

In [9]:
clf.predict(X_test)

array([2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 4, 4, 4, 2, 2, 2, 2, 2, 4, 4, 2, 4,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 4, 2, 4, 2, 2, 2, 2,
       2, 2, 2, 4, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 4, 4, 2, 4, 4, 2,
       2, 4, 4, 2, 2, 4, 4, 2, 4, 2, 2, 4, 4, 4, 2, 2, 4, 2, 2, 4, 4, 4,
       4, 4, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 4, 4, 2, 2, 4, 4, 2, 2, 2,
       4, 2, 2, 4, 2, 2, 2, 4, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 2, 2,
       2, 4, 2, 2, 2, 2, 2, 2], dtype=int64)

In [10]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
prediction = clf.predict(X_test)
print("Confusion Matrix:")
print(confusion_matrix(y_test,prediction))
print("Classification Report:")
print(classification_report(y_test,prediction))

[[87  2]
 [ 4 47]]
              precision    recall  f1-score   support

           2       0.96      0.98      0.97        89
           4       0.96      0.92      0.94        51

    accuracy                           0.96       140
   macro avg       0.96      0.95      0.95       140
weighted avg       0.96      0.96      0.96       140



In [11]:
parameters = {
'solver': ['adam', 'lbfgs', 'sgd'],
'max_iter': [1000, 1200, 1500, 2000],
'hidden_layer_sizes': [(10,10,10), (10, 5), (5,5), (100, 10, 50)],
'alpha': [.0001, .005],
'learning_rate': ['constant', 'adaptive']
}

In [15]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.svm import SVC
gs = GridSearchCV(estimator=clf, param_grid=parameters, cv=3).fit(X_train, y_train)
print("Best parameters set found on development set:")
print()
print(gs.best_params_)

C:\Users\Logan\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\Logan\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\Logan\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\Logan\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1200) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\Logan\anaconda3\lib\site-packages\sklearn\neural_network\_m

Best parameters set found on development set:

{'alpha': 0.005, 'hidden_layer_sizes': (10, 5), 'learning_rate': 'constant', 'max_iter': 1200, 'solver': 'adam'}


In [20]:
print("The best parameters are: {'alpha': 0.005, 'hidden_layer_sizes': (10, 5), 'learning_rate': 'constant', 'max_iter': 1200, 'solver': 'adam'}")
print("Grid scores on development set:")
print()
means = gs.cv_results_['mean_test_score']
stds = gs.cv_results_['std_test_score']
for mean, std, params in zip(means, stds, gs.cv_results_['params']):
    print("Mean: %0.3f Std Dev: (+/-%0.03f) for the following Parameters: %r"
        % (mean, std * 2, params))

The best parameters are: {'alpha': 0.005, 'hidden_layer_sizes': (10, 5), 'learning_rate': 'constant', 'max_iter': 1200, 'solver': 'adam'}
Grid scores on development set:

Mean: 0.943 Std Dev: (+/-0.013) for the following Parameters: {'alpha': 0.0001, 'hidden_layer_sizes': (10, 10, 10), 'learning_rate': 'constant', 'max_iter': 1000, 'solver': 'adam'}
Mean: 0.946 Std Dev: (+/-0.030) for the following Parameters: {'alpha': 0.0001, 'hidden_layer_sizes': (10, 10, 10), 'learning_rate': 'constant', 'max_iter': 1000, 'solver': 'lbfgs'}
Mean: 0.957 Std Dev: (+/-0.023) for the following Parameters: {'alpha': 0.0001, 'hidden_layer_sizes': (10, 10, 10), 'learning_rate': 'constant', 'max_iter': 1000, 'solver': 'sgd'}
Mean: 0.957 Std Dev: (+/-0.018) for the following Parameters: {'alpha': 0.0001, 'hidden_layer_sizes': (10, 10, 10), 'learning_rate': 'constant', 'max_iter': 1200, 'solver': 'adam'}
Mean: 0.937 Std Dev: (+/-0.036) for the following Parameters: {'alpha': 0.0001, 'hidden_layer_sizes': (10

In [21]:
prediction = gs.predict(X_test)
print("Confusion Matrix:")
print(confusion_matrix(y_test,prediction))
print("Classification Report:")
print(classification_report(y_test,prediction))

Confusion Matrix:
[[87  2]
 [ 3 48]]
Classification Report:
              precision    recall  f1-score   support

           2       0.97      0.98      0.97        89
           4       0.96      0.94      0.95        51

    accuracy                           0.96       140
   macro avg       0.96      0.96      0.96       140
weighted avg       0.96      0.96      0.96       140



In [39]:
for mean, std, params in zip(means, stds, gs.cv_results_['params']):
    if (params['solver'] == 'lbfgs') and (mean<.9):
        print("Mean: %0.3f Std Dev: (+/-%0.03f) for the following Parameters: %r"
            % (mean, std * 2, params))

Mean: 0.862 Std Dev: (+/-0.284) for the following Parameters: {'alpha': 0.0001, 'hidden_layer_sizes': (10, 5), 'learning_rate': 'adaptive', 'max_iter': 2000, 'solver': 'lbfgs'}
Mean: 0.850 Std Dev: (+/-0.272) for the following Parameters: {'alpha': 0.005, 'hidden_layer_sizes': (10, 5), 'learning_rate': 'adaptive', 'max_iter': 1200, 'solver': 'lbfgs'}
Mean: 0.859 Std Dev: (+/-0.285) for the following Parameters: {'alpha': 0.005, 'hidden_layer_sizes': (5, 5), 'learning_rate': 'adaptive', 'max_iter': 2000, 'solver': 'lbfgs'}


In [61]:
parameters = {
'solver': ['adam'],
'max_iter': [1000, 20],
'hidden_layer_sizes': [(10, 5), (5,5)],
'alpha': [.001],
'learning_rate': ['constant']
}
gs = GridSearchCV(estimator=clf, param_grid=parameters, cv=3).fit(X_train, y_train)


C:\Users\Logan\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\Logan\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\Logan\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\Logan\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\Logan\anaconda3\lib\site-packages\sklearn\neural_network\_multilaye

In [62]:
print("Best parameters set found on development set:")
print()
print(gs.best_params_)
means = gs.cv_results_['mean_test_score']
stds = gs.cv_results_['std_test_score']
for mean, std, params in zip(means, stds, gs.cv_results_['params']):
    print("Mean: %0.3f Std Dev: (+/-%0.03f) for the following Parameters: %r"
        % (mean, std * 2, params))

Best parameters set found on development set:

{'alpha': 0.001, 'hidden_layer_sizes': (5, 5), 'learning_rate': 'constant', 'max_iter': 1000, 'solver': 'adam'}
Mean: 0.946 Std Dev: (+/-0.023) for the following Parameters: {'alpha': 0.001, 'hidden_layer_sizes': (10, 5), 'learning_rate': 'constant', 'max_iter': 1000, 'solver': 'adam'}
Mean: 0.787 Std Dev: (+/-0.183) for the following Parameters: {'alpha': 0.001, 'hidden_layer_sizes': (10, 5), 'learning_rate': 'constant', 'max_iter': 20, 'solver': 'adam'}
Mean: 0.955 Std Dev: (+/-0.018) for the following Parameters: {'alpha': 0.001, 'hidden_layer_sizes': (5, 5), 'learning_rate': 'constant', 'max_iter': 1000, 'solver': 'adam'}
Mean: 0.585 Std Dev: (+/-0.434) for the following Parameters: {'alpha': 0.001, 'hidden_layer_sizes': (5, 5), 'learning_rate': 'constant', 'max_iter': 20, 'solver': 'adam'}


In [ ]:
adam best : Mean: 0.966 Std Dev: (+/-0.005) for the following Parameters: {'alpha': 0.005, 'hidden_layer_sizes': (10, 5), 'learning_rate': 'constant', 'max_iter': 1200, 'solver': 'adam'}
adam worst : Mean: 0.862 Std Dev: (+/-0.284) for the following Parameters: {'alpha': 0.005, 'hidden_layer_sizes': (5, 5), 'learning_rate': 'adaptive', 'max_iter': 1200, 'solver': 'adam'}
sgd best: Mean: 0.959 Std Dev: (+/-0.005) for the following Parameters: {'alpha': 0.0001, 'hidden_layer_sizes': (100, 10, 50), 'learning_rate': 'constant', 'max_iter': 1200, 'solver': 'sgd'}
sgd worst: Mean: 0.857 Std Dev: (+/-0.277) for the following Parameters: {'alpha': 0.005, 'hidden_layer_sizes': (5, 5), 'learning_rate': 'adaptive', 'max_iter': 1000, 'solver': 'sgd'}
lbfgs best: Mean: 0.966 Std Dev: (+/-0.025) for the following Parameters: {'alpha': 0.005, 'hidden_layer_sizes': (5, 5), 'learning_rate': 'adaptive', 'max_iter': 1200, 'solver': 'lbfgs'}
lbfgs worst: Mean: 0.850 Std Dev: (+/-0.272) for the following Parameters: {'alpha': 0.005, 'hidden_layer_sizes': (10, 5), 'learning_rate': 'adaptive', 'max_iter': 1200, 'solver': 'lbfgs'}
                
                